SELECT COUNT(DISTINCT (S_I_ID)) AS STOCK_COUNT
FROM ORDER_LINE, STOCK
WHERE OL_W_ID = 1
AND OL_D_ID = 1
AND OL_O_ID < 2121
AND OL_O_ID >= 2101
AND S_W_ID = 1
AND S_I_ID = OL_I_ID
AND S_QUANTITY < 20;
